import { ContainerEngineInfo, SystemOverview } from "@/types";

export const DEFAULT_ENGINES: ContainerEngineInfo[] = [
  {
    id: "docker-desktop",
    name: "Docker Desktop",
    type: "docker-desktop",
    socketPath: "/var/run/docker.sock",
    appPath: "/Applications/Docker.app",
    status: "stopped",
    isDefault: true,
    isActive: true,
    description: "Official Docker Desktop daemon & VM",
    icon: "docker",
  },
  {
    id: "orbstack",
    name: "OrbStack",
    type: "orbstack",
    socketPath: "/var/run/docker.sock",
    appPath: "/Applications/OrbStack.app",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Ultra-fast, lightweight Docker & Linux alternative",
    icon: "orbstack",
  },
  {
    id: "rancher",
    name: "Rancher Desktop",
    type: "rancher",
    socketPath: "/var/run/docker.sock",
    appPath: "/Applications/Rancher Desktop.app",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Container management and local Kubernetes",
    icon: "rancher",
  },
  {
    id: "colima",
    name: "Colima",
    type: "colima",
    socketPath: "/var/run/docker.sock",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Minimal container runtimes on macOS with Lima",
    icon: "colima",
  },
  {
    id: "podman",
    name: "Podman",
    type: "podman",
    socketPath: "/var/run/podman/podman.sock",
    appPath: "/Applications/Podman Desktop.app",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Daemonless container engine by Red Hat",
    icon: "podman",
  },
];

export const DEFAULT_OVERVIEW: SystemOverview = {
  dockerConnected: false,
  engineVersion: "",
  operatingSystem: "",
  architecture: "",
  totalContainers: 0,
  runningContainers: 0,
  stoppedContainers: 0,
  pausedContainers: 0,
  totalImages: 0,
  totalVolumes: 0,
  totalNetworks: 0,
  systemCpuPercent: 0,
  systemMemoryTotal: 0,
  systemMemoryUsed: 0,
  hostName: "localhost",
  activeHost: "Docker Desktop",
  isMockData: false,
  activeEngine: DEFAULT_ENGINES[0],
  detectedEngines: DEFAULT_ENGINES,
};