import { ContainerEngineInfo, SystemOverview } from "@/types";
import { isWindows } from "@/lib/platform";

export const DEFAULT_ENGINES: ContainerEngineInfo[] = [
  {
    id: "docker-desktop",
    name: "Docker Desktop",
    type: "docker-desktop",
    socketPath: isWindows ? "//./pipe/docker_engine" : "/var/run/docker.sock",
    appPath: isWindows ? undefined : "/Applications/Docker.app",
    status: "stopped",
    isDefault: true,
    isActive: true,
    description: "Official Docker Desktop daemon & VM",
    icon: "docker",
  },
  {
    id: "orbstack",
    name: "OrbStack",
    type: "orbstack",
    socketPath: "/var/run/docker.sock",
    appPath: "/Applications/OrbStack.app",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Ultra-fast, lightweight Docker & Linux alternative",
    icon: "orbstack",
  },
  {
    id: "rancher",
    name: "Rancher Desktop",
    type: "rancher",
    socketPath: "/var/run/docker.sock",
    appPath: "/Applications/Rancher Desktop.app",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Container management and local Kubernetes",
    icon: "rancher",
  },
  {
    id: "colima",
    name: "Colima",
    type: "colima",
    socketPath: "/var/run/docker.sock",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Minimal container runtimes on macOS with Lima",
    icon: "colima",
  },
  {
    id: "podman",
    name: "Podman",
    type: "podman",
    socketPath: "/var/run/podman/podman.sock",
    appPath: "/Applications/Podman Desktop.app",
    status: "not_installed",
    isDefault: false,
    isActive: false,
    description: "Daemonless container engine by Red Hat",
    icon: "podman",
  },
];

export const DEFAULT_OVERVIEW: SystemOverview = {
  dockerConnected: false,
  engineVersion: "",
  operatingSystem: "",
  architecture: "",
  totalContainers: 0,
  runningContainers: 0,
  stoppedContainers: 0,
  pausedContainers: 0,
  totalImages: 0,
  totalVolumes: 0,
  totalNetworks: 0,
  systemCpuPercent: 0,
  systemMemoryTotal: 0,
  systemMemoryUsed: 0,
  hostName: "localhost",
  activeHost: "Docker Desktop",
  isMockData: false,
  activeEngine: DEFAULT_ENGINES[0],
  detectedEngines: DEFAULT_ENGINES,
};

export const DEFAULT_IMAGES = [
  {
    id: "sha256:7264a8db6415f01e",
    repository: "node",
    tag: "20-alpine",
    size: 178 * 1024 * 1024,
    created: new Date(Date.now() - 5 * 86400000).toISOString(),
    inUse: true,
    containerCount: 1,
  },
  {
    id: "sha256:4c728e91d8f3a92b",
    repository: "redis",
    tag: "7-alpine",
    size: 34 * 1024 * 1024,
    created: new Date(Date.now() - 14 * 86400000).toISOString(),
    inUse: true,
    containerCount: 1,
  },
  {
    id: "sha256:e1a90c41f71290bb",
    repository: "postgres",
    tag: "16-alpine",
    size: 245 * 1024 * 1024,
    created: new Date(Date.now() - 20 * 86400000).toISOString(),
    inUse: false,
    containerCount: 0,
  },
  {
    id: "sha256:aa91280fc29168aa",
    repository: "nginx",
    tag: "alpine",
    size: 42 * 1024 * 1024,
    created: new Date(Date.now() - 28 * 86400000).toISOString(),
    inUse: false,
    containerCount: 0,
  },
];
